package com.smallchill.modules.app.model;

import com.smallchill.core.base.model.BaseModel;
import org.beetl.sql.core.annotatoin.Table;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-09 18:24:22
 */
@Table(name = "tb_recharge_card")
@SuppressWarnings("serial")
public class RechargeCard extends BaseModel {

	private Integer id; //主键
	private Integer card_number; //充值卡库存
	private Integer is_deleted; //是否已删除
	private String card_name; //充值卡名称
	private String card_photo; //充值卡照片
	private String card_price; //充值卡价格
	private Date create_time; //创建时间
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getCard_number() {
		return card_number;
	}
	
	public void setCard_number(Integer card_number) {
		this.card_number = card_number;
	}
	
	public Integer getIs_deleted() {
		return is_deleted;
	}
	
	public void setIs_deleted(Integer is_deleted) {
		this.is_deleted = is_deleted;
	}
	
	public String getCard_name() {
		return card_name;
	}
	
	public void setCard_name(String card_name) {
		this.card_name = card_name;
	}
	
	public String getCard_photo() {
		return card_photo;
	}
	
	public void setCard_photo(String card_photo) {
		this.card_photo = card_photo;
	}
	
	public String getCard_price() {
		return card_price;
	}
	
	public void setCard_price(String card_price) {
		this.card_price = card_price;
	}
	
	public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	

}
