package com.smallchill.modules.app.model;

import com.smallchill.core.base.model.BaseModel;
import org.beetl.sql.core.annotatoin.InsertIgnore;
import org.beetl.sql.core.annotatoin.Table;
import org.beetl.sql.core.annotatoin.UpdateIgnore;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-09 18:24:22
 */
@Table(name = "tb_shop")
@SuppressWarnings("serial")
public class Shop extends BaseModel {

	private Integer id; //主键
	private Integer is_deleted; //是否已删除
	private String coordinate; //门店经纬度
	private String info; //门店介绍
	private String name; //门店名称
    private String phone; //负责人手机
	private Date create_time; //创建时间
    @InsertIgnore
    @UpdateIgnore
    private double distance; //距离
    @InsertIgnore
    @UpdateIgnore
    private double longitude; //纬度
    @InsertIgnore
    @UpdateIgnore
    private double latitude; //经度
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getIs_deleted() {
		return is_deleted;
	}
	
	public void setIs_deleted(Integer is_deleted) {
		this.is_deleted = is_deleted;
	}
	
	public String getCoordinate() {
		return coordinate;
	}
	
	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}
	
	public String getInfo() {
		return info;
	}
	
	public void setInfo(String info) {
		this.info = info;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
}
