package com.smallchill.modules.app.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.modules.app.model.Proceeds;

import java.util.Map;

/**
 * Generated by Blade.
 * 2018-01-07 12:18:34
 */
public interface ProceedsService extends IService<Proceeds> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

}
