package com.smallchill.modules.bill.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.smallchill.core.base.model.BaseModel;
import org.beetl.sql.core.annotatoin.Table;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-12-29 13:13:42
 */
@Table(name = "tb_bill")
@SuppressWarnings("serial")
public class Bill extends BaseModel {

	private Integer id; //主键
    @JSONField(name = "BillDate")
    private String BillDate; //开票时间
    @JSONField(name = "BillBalance")
	private String BillBalance; //开票金额
    @JSONField(name = "BillNo")
	private String BillNo; //发票号
    @JSONField(name = "BillNumber")
	private String BillNumber; //数量
    @JSONField(name = "BillPage")
	private String BillPage; //页数
    @JSONField(name = "BillPerson")
	private String BillPerson; //签收人
    @JSONField(name = "BillTips")
	private String BillTips; //摘要
    @JSONField(name = "BillUnit")
	private String BillUnit; //单位
    @JSONField(name = "CustName")
	private String CustName; //公司名称
    @JSONField(name = "CustNo")
	private String CustNo; //企业代号
    @JSONField(name = "CreateTime")
	private Date CreateTime; //创建时间
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

    public String getBillDate() {
        return BillDate;
    }

    public void setBillDate(String billDate) {
        BillDate = billDate;
    }

    public String getBillBalance() {
		return BillBalance;
	}
	
	public void setBillBalance(String BillBalance) {
		this.BillBalance = BillBalance;
	}
	
	public String getBillNo() {
		return BillNo;
	}
	
	public void setBillNo(String BillNo) {
		this.BillNo = BillNo;
	}
	
	public String getBillNumber() {
		return BillNumber;
	}
	
	public void setBillNumber(String BillNumber) {
		this.BillNumber = BillNumber;
	}
	
	public String getBillPage() {
		return BillPage;
	}
	
	public void setBillPage(String BillPage) {
		this.BillPage = BillPage;
	}
	
	public String getBillPerson() {
		return BillPerson;
	}
	
	public void setBillPerson(String BillPerson) {
		this.BillPerson = BillPerson;
	}
	
	public String getBillTips() {
		return BillTips;
	}
	
	public void setBillTips(String BillTips) {
		this.BillTips = BillTips;
	}
	
	public String getBillUnit() {
		return BillUnit;
	}
	
	public void setBillUnit(String BillUnit) {
		this.BillUnit = BillUnit;
	}
	
	public String getCustName() {
		return CustName;
	}
	
	public void setCustName(String CustName) {
		this.CustName = CustName;
	}
	
	public String getCustNo() {
		return CustNo;
	}
	
	public void setCustNo(String CustNo) {
		this.CustNo = CustNo;
	}
	
	public Date getCreateTime() {
		return CreateTime;
	}
	
	public void setCreateTime(Date CreateTime) {
		this.CreateTime = CreateTime;
	}
	

}
