package com.smallchill.modules.charge.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.modules.charge.model.Bank;

import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-13 20:35:54
 */
public interface BankService extends IService<Bank> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

}
