package com.smallchill.modules.charge.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.modules.charge.model.Charge;

import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-10 01:09:32
 */
public interface ChargeService extends IService<Charge> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

	boolean updateCharge(Charge charge);

    boolean audit(Charge charge);

    boolean cancel(String id, String OrderNo);

}
