package com.smallchill.modules.platform.service;

import com.smallchill.core.annotation.DoLog;
import com.smallchill.core.base.service.IService;
import com.smallchill.modules.charge.model.Charge;
import com.smallchill.modules.charge.model.ChargeList;
import com.smallchill.modules.platform.model.ICCard;

import java.util.List;
import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-09 15:42:39
 */
public interface ICCardService extends IService<ICCard> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

	@DoLog("创建充值订单")
	boolean saveCharge(Charge charge, List<ChargeList> chargeList);

}
