package com.smallchill.modules.platform.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.modules.platform.model.OilTrade;

import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-22 11:11:39
 */
public interface OilTradeService extends IService<OilTrade> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

}
