package com.smallchill.modules.platform.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.modules.platform.model.Station;

import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-09 15:42:39
 */
public interface StationService extends IService<Station> {
	
	boolean updateStatus(String ids, Integer status);
	
	Map<String, Object> findOne(Object id);

}
