package com.smallchill.modules.platform.service;

import com.smallchill.core.annotation.DoLog;

/**
 * Generated by Blade.
 * 2017-09-09 15:42:39
 */
public interface SyncService {

    @DoLog("数据同步")
	boolean saveSync();
    @DoLog("数据全部同步")
    boolean saveSyncAll();
    @DoLog("数据同步卡号信息")
    boolean saveCard();
    @DoLog("数据同步消费信息")
    boolean saveOil();
    @DoLog("数据同步站点和部门")
    boolean saveStationAndDept();
}
