package com.smallchill.modules.platform.controller;

import com.smallchill.common.base.BaseController;
import com.smallchill.core.annotation.Json;
import com.smallchill.core.toolbox.ApiResult;
import com.smallchill.core.toolbox.CMap;
import com.smallchill.core.toolbox.kit.JsonKit;
import com.smallchill.modules.platform.model.Investor;
import com.smallchill.modules.platform.service.InvestorService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * Generated by Blade.
 * 2017-09-26 18:12:48
 */
@Controller
@RequestMapping("/investor")
public class InvestorController extends BaseController {
	private static String CODE = "investor";
	private static String PREFIX = "tb_investor";
	private static String LIST_SOURCE = "investor.list";
	private static String BASE_PATH = "/modules/platform/investor/";
	
	@Autowired
    InvestorService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "investor.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "investor_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable Integer id, ModelMap mm) {
		Investor investor = service.findById(id);
		mm.put("model", JsonKit.toJson(investor));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "investor_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable Integer id, ModelMap mm) {
		Investor investor = service.findById(id);
		mm.put("model", JsonKit.toJson(investor));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "investor_view.html";
	}

	@Json
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@Json
	@RequestMapping(KEY_SAVE)
	public ApiResult save() {
		Investor investor = mapping(PREFIX, Investor.class);
        boolean temp = service.saveInvestor(investor);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@Json
	@RequestMapping(KEY_UPDATE)
	public ApiResult update() {
		Investor investor = mapping(PREFIX, Investor.class);
		boolean temp = service.updateInvestor(investor);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@Json
	@RequestMapping(KEY_REMOVE)
	public ApiResult remove(@RequestParam String ids) {
		boolean temp = service.updateBy("IsDeleted = 1", "id in (#{join(ids)})", CMap.init().set("ids", toIntArray(ids)));
		if (temp) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
