package com.smallchill.modules.platform.controller;

import com.smallchill.common.base.BaseController;
import com.smallchill.common.tool.SysCache;
import com.smallchill.core.annotation.Json;
import com.smallchill.core.aop.AopContext;
import com.smallchill.core.meta.PageIntercept;
import com.smallchill.core.plugins.dao.Db;
import com.smallchill.core.toolbox.grid.BladePage;
import com.smallchill.core.toolbox.grid.JqGrid;
import com.smallchill.core.toolbox.kit.JsonKit;
import com.smallchill.modules.platform.model.ICCard;
import com.smallchill.modules.platform.model.OilTrade;
import com.smallchill.modules.platform.service.OilTradeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-22 11:11:39
 */
@Controller
@RequestMapping("/oilTradeCust")
public class OilTradeCustController extends BaseController {
	private static String CODE = "oilTradeCust";
	private static String PREFIX = "tb_oil_trade";
	private static String LIST_SOURCE = "oilTrade.list";
	private static String BASE_PATH = "/modules/platform/oilTrade/";
	
	@Autowired
    OilTradeService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "oilTradeCust.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable Integer id, ModelMap mm) {
		OilTrade oilTrade = service.findById(id);
		mm.put("model", JsonKit.toJson(oilTrade));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "oilTradeCust_view.html";
	}

	@Json
	@RequestMapping(KEY_LIST)
	public JqGrid<Map<String, Object>> list() {
        final Map[] sum = {new HashMap()};

        JqGrid<Map<String, Object>> grid = (JqGrid<Map<String, Object>>) paginate(LIST_SOURCE, new PageIntercept(){
            @Override
            public void queryBefore(AopContext ac) {

                Map<String, Object> param = ac.getParam();
                StringBuilder sb = new StringBuilder();
                if (param.get("OilTime_start_skip_true") != null) {
                    sb.append(" and OilTime >= #{OilTime_start_skip_true} ");
                }
                if (param.get("OilTime_end_skip_true") != null) {
                    sb.append(" and OilTime <= #{OilTime_end_skip_true} ");
                }
                if (param.get("CarNo_skip_true") != null) {
                    sb.append(" and CardNo in (#{join(CardNoExt)}) ");
                    String cards = SysCache.getCardsByCarNo(param.get("CarNo_skip_true"));
                    param.put("CardNoExt", cards.split(","));
                }

                ac.setCondition(sb.toString());

                ac.setSqlCount("select count(1) from tb_oil_trade" + ac.getSqlEx() + sb.toString());

                sum[0] = Db.selectOne("select sum(Qty) qty, SUM(TradeMoney) tra from tb_oil_trade" + ac.getSqlEx() + sb.toString(), param);

            }

            @Override
            public void queryAfter(AopContext ac) {
                BladePage<Map<String, Object>> page = (BladePage<Map<String, Object>>) ac.getObject();
                List<Map<String, Object>> list = page.getRows();
                for (Map<String, Object> map : list) {
                    ICCard card = SysCache.getCard(map.get("CardNo"));
                    if (null != card) {
                        map.put("CarNo", card.getCarNo());
                        map.put("CardSerialNo", card.getCardSerialNo());
                        map.put("ReserveFund", card.getReserveFund());
                    }
                }
            }
        });

        grid.setExt(sum[0]);

		return grid;
	}

    @Json
    @RequestMapping("listOne")
    public Object listOne() {
        Object grid = paginate(LIST_SOURCE, new PageIntercept(){
            @Override
            public void queryBefore(AopContext ac) {
                String cardNo = ac.getCtrl().getParameter("CardNo");
                ac.getParam().put("cardNo", cardNo);
                ac.setCondition("and CardNo = #{cardNo} ");
            }
        });
        return grid;
    }

}
