package com.smallchill.modules.charge.model;

import com.smallchill.core.base.model.BaseModel;
import org.beetl.sql.core.annotatoin.Table;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-09-13 20:35:54
 */
@Table(name = "tb_bank")
@SuppressWarnings("serial")
public class Bank extends BaseModel {

	private Integer id; //主键
	private String BankName; //开户行
	private String BankNo; //开户行账号
	private String CompanyAddress; //公司地址
	private String CompanyName; //公司名称
	private String IdNumber; //纳税人识别号
	private Date CreateTime;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getBankName() {
		return BankName;
	}
	
	public void setBankName(String BankName) {
		this.BankName = BankName;
	}
	
	public String getBankNo() {
		return BankNo;
	}
	
	public void setBankNo(String BankNo) {
		this.BankNo = BankNo;
	}
	
	public String getCompanyAddress() {
		return CompanyAddress;
	}
	
	public void setCompanyAddress(String CompanyAddress) {
		this.CompanyAddress = CompanyAddress;
	}
	
	public String getCompanyName() {
		return CompanyName;
	}
	
	public void setCompanyName(String CompanyName) {
		this.CompanyName = CompanyName;
	}
	
	public String getIdNumber() {
		return IdNumber;
	}
	
	public void setIdNumber(String IdNumber) {
		this.IdNumber = IdNumber;
	}
	
	public Date getCreateTime() {
		return CreateTime;
	}
	
	public void setCreateTime(Date CreateTime) {
		this.CreateTime = CreateTime;
	}
	

}
