package com.smallchill.modules.charge.service.impl;

import com.smallchill.core.base.service.BaseService;
import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.plugins.dao.Md;
import com.smallchill.core.toolbox.CMap;
import com.smallchill.core.toolbox.support.Convert;
import com.smallchill.modules.charge.model.Charge;
import com.smallchill.modules.charge.model.ChargeList;
import com.smallchill.modules.charge.service.ChargeService;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * Generated by Blade.
 * 2017-09-10 01:09:32
 */
@Service
public class ChargeServiceImpl extends BaseService<Charge> implements ChargeService {

	@Override
	public boolean updateStatus(String ids, Integer status) {
		StringBuilder sb = new StringBuilder(" status = #{status} ");
		CMap map = CMap.init().set("status", status).set("ids", Convert.toIntArray(ids));
		boolean temp = updateBy(sb.toString(), "id in (#{join(ids)})", map);
		return temp;
	}

	@Override
	@SuppressWarnings("unchecked")
	public Map<String, Object> findOne(Object id) {
		return Md.selectOne("charge.findOne", CMap.init().set("id", id), Map.class);
	}

    @Override
    public boolean updateCharge(Charge charge) {
        Charge old = findById(charge.getId());
        update(charge);
        Blade.create(ChargeList.class).updateBy("OrderNo = #{new}", "OrderNo = #{old}", CMap.init().set("new", charge.getOrderNo()).set("old", old.getOrderNo()));
        return true;
    }

    @Override
    public boolean audit(Charge charge) {
	    update(charge);
	    Blade.create(ChargeList.class).updateBy("Status = #{Status}", "OrderNo = #{OrderNo}", charge);
        return true;
    }

    @Override
    public boolean cancel(String id, String OrderNo) {
        Blade.create(Charge.class).updateBy("IsDeleted = 1, Status = 5", "id = #{id}", CMap.init().set("id", id));
        Blade.create(ChargeList.class).updateBy("IsDeleted = 1, Status = 5", "OrderNo = #{OrderNo}", CMap.init().set("OrderNo", OrderNo));
        return true;
    }

}
