package com.smallchill.modules.platform.model;


import com.alibaba.fastjson.annotation.JSONField;
import com.smallchill.core.base.model.BaseModel;
import com.smallchill.core.toolbox.kit.StrKit;
import org.beetl.sql.core.annotatoin.AssignID;
import org.beetl.sql.core.annotatoin.Table;

/**
 * Generated by Blade.
 * 2017-09-09 15:42:39
 */
@Table(name = "tb_iccard")
@SuppressWarnings("serial")
public class ICCard extends BaseModel {

    //主键
    @AssignID
    private String id;
    //地址
    @JSONField(name = "Address")
    private String Address;
    //卡余额
    @JSONField(name = "Balance")
    private String Balance;
    //生日
    @JSONField(name = "Birthday")
    private String Birthday;
    //车号
    @JSONField(name = "CarNo")
    private String CarNo;
    //车型
    @JSONField(name = "CarType")
    private String CarType;
    //卡号
    @JSONField(name = "CardNo")
    private String CardNo;
    //印刷号
    @JSONField(name = "CardSerialNo")
    private String CardSerialNo;
    //卡状态(0:代售、2:正常、3:灰卡、4:挂失、6:报废、7:销户)
    @JSONField(name = "CardStatus")
    private String CardStatus;
    //卡状态名称
    @JSONField(name = "CardStatusName")
    private String CardStatusName;
    //市
    @JSONField(name = "City")
    private String City;
    //县
    @JSONField(name = "County")
    private String County;
    //客户名称
    @JSONField(name = "CustName")
    private String CustName;
    //客户代码
    @JSONField(name = "CustNo")
    private String CustNo;
    //日限加金额
    @JSONField(name = "DailyAmount")
    private String DailyAmount;
    //日限加次数
    @JSONField(name = "DailyTimes")
    private String DailyTimes;
    //部门名称
    @JSONField(name = "DepartName")
    private String DepartName;
    //部门编号
    @JSONField(name = "DepartNo")
    private String DepartNo;
    //邮箱
    @JSONField(name = "Email")
    private String Email;
    //截止日期
    @JSONField(name = "ExpiringDate")
    private String ExpiringDate;
    //证件号
    @JSONField(name = "HolderID")
    private String HolderID;
    //证件类型(0:身份证、1:军官证、2:护照、3:入境证、4:临时身份证、5:驾驶证、6:组织机构代码、7:其他)
    @JSONField(name = "HolderIDType")
    private String HolderIDType;
    //证件类型名称
    @JSONField(name = "HolderIDTypeName")
    private String HolderIDTypeName;
    //持卡人姓名
    @JSONField(name = "HolderName")
    private String HolderName;
    //旧卡卡号
    @JSONField(name = "LastCardNo")
    private String LastCardNo;
    //末次操作时间
    @JSONField(name = "LastOperateTime")
    private String LastOperateTime;
    //是否限车加油(0:不限、1:限)
    @JSONField(name = "LimitCar")
    private String LimitCar;
    //是否限站加油(0:不限、1:限)
    @JSONField(name = "LimitStation")
    private String LimitStation;
    //制卡时间
    @JSONField(name = "MakeTime")
    private String MakeTime;
    //限加油品代码
    @JSONField(name = "OilCode")
    private String OilCode;
    //启用日期
    @JSONField(name = "OpeningDate")
    private String OpeningDate;
    //次限加油量
    @JSONField(name = "PerAmount")
    private String PerAmount;
    //次限加油单位(0:元、1:升)
    @JSONField(name = "PerAmountUnit")
    private String PerAmountUnit;
    //积分余额
    @JSONField(name = "PointsBalance")
    private String PointsBalance;
    @JSONField(name = "PrePaid")
    private String PrePaid;
    @JSONField(name = "PreferentialRefund")
    private String PreferentialRefund;
    //省
    @JSONField(name = "Province")
    private String Province;
    //卡备用金额
    @JSONField(name = "ReserveFund")
    private String ReserveFund;
    //结算单位(0:元、1:升)
    @JSONField(name = "SettlementUnite")
    private String SettlementUnite;
    //结算单位名称
    @JSONField(name = "SettlementUniteName")
    private String SettlementUniteName;
    //限加油站列表
    @JSONField(name = "StationList")
    private String StationList;
    //电话
    @JSONField(name = "TelNo")
    private String TelNo;

    public String getId() {
        if (StrKit.isBlank(id))
            return CardNo;
        else
            return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getBalance() {
        return Balance;
    }

    public void setBalance(String Balance) {
        this.Balance = Balance;
    }

    public String getBirthday() {
        return Birthday;
    }

    public void setBirthday(String Birthday) {
        this.Birthday = Birthday;
    }

    public String getCarNo() {
        return CarNo;
    }

    public void setCarNo(String CarNo) {
        this.CarNo = CarNo;
    }

    public String getCarType() {
        return CarType;
    }

    public void setCarType(String CarType) {
        this.CarType = CarType;
    }

    public String getCardNo() {
        return CardNo;
    }

    public void setCardNo(String CardNo) {
        this.CardNo = CardNo;
    }

    public String getCardSerialNo() {
        return CardSerialNo;
    }

    public void setCardSerialNo(String CardSerialNo) {
        this.CardSerialNo = CardSerialNo;
    }

    public String getCardStatus() {
        return CardStatus;
    }

    public void setCardStatus(String CardStatus) {
        this.CardStatus = CardStatus;
    }

    public String getCardStatusName() {
        return CardStatusName;
    }

    public void setCardStatusName(String CardStatusName) {
        this.CardStatusName = CardStatusName;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getCounty() {
        return County;
    }

    public void setCounty(String County) {
        this.County = County;
    }

    public String getCustName() {
        return CustName;
    }

    public void setCustName(String CustName) {
        this.CustName = CustName;
    }

    public String getCustNo() {
        return CustNo;
    }

    public void setCustNo(String CustNo) {
        this.CustNo = CustNo;
    }

    public String getDailyAmount() {
        return DailyAmount;
    }

    public void setDailyAmount(String DailyAmount) {
        this.DailyAmount = DailyAmount;
    }

    public String getDailyTimes() {
        return DailyTimes;
    }

    public void setDailyTimes(String DailyTimes) {
        this.DailyTimes = DailyTimes;
    }

    public String getDepartName() {
        return DepartName;
    }

    public void setDepartName(String DepartName) {
        this.DepartName = DepartName;
    }

    public String getDepartNo() {
        return DepartNo;
    }

    public void setDepartNo(String DepartNo) {
        this.DepartNo = DepartNo;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getExpiringDate() {
        return ExpiringDate;
    }

    public void setExpiringDate(String ExpiringDate) {
        this.ExpiringDate = ExpiringDate;
    }

    public String getHolderID() {
        return HolderID;
    }

    public void setHolderID(String HolderID) {
        this.HolderID = HolderID;
    }

    public String getHolderIDType() {
        return HolderIDType;
    }

    public void setHolderIDType(String HolderIDType) {
        this.HolderIDType = HolderIDType;
    }

    public String getHolderIDTypeName() {
        return HolderIDTypeName;
    }

    public void setHolderIDTypeName(String HolderIDTypeName) {
        this.HolderIDTypeName = HolderIDTypeName;
    }

    public String getHolderName() {
        return HolderName;
    }

    public void setHolderName(String HolderName) {
        this.HolderName = HolderName;
    }

    public String getLastCardNo() {
        return LastCardNo;
    }

    public void setLastCardNo(String LastCardNo) {
        this.LastCardNo = LastCardNo;
    }

    public String getLastOperateTime() {
        return LastOperateTime;
    }

    public void setLastOperateTime(String LastOperateTime) {
        this.LastOperateTime = LastOperateTime;
    }

    public String getLimitCar() {
        return LimitCar;
    }

    public void setLimitCar(String LimitCar) {
        this.LimitCar = LimitCar;
    }

    public String getLimitStation() {
        return LimitStation;
    }

    public void setLimitStation(String LimitStation) {
        this.LimitStation = LimitStation;
    }

    public String getMakeTime() {
        return MakeTime;
    }

    public void setMakeTime(String MakeTime) {
        this.MakeTime = MakeTime;
    }

    public String getOilCode() {
        return OilCode;
    }

    public void setOilCode(String OilCode) {
        this.OilCode = OilCode;
    }

    public String getOpeningDate() {
        return OpeningDate;
    }

    public void setOpeningDate(String OpeningDate) {
        this.OpeningDate = OpeningDate;
    }

    public String getPerAmount() {
        return PerAmount;
    }

    public void setPerAmount(String PerAmount) {
        this.PerAmount = PerAmount;
    }

    public String getPerAmountUnit() {
        return PerAmountUnit;
    }

    public void setPerAmountUnit(String PerAmountUnit) {
        this.PerAmountUnit = PerAmountUnit;
    }

    public String getPointsBalance() {
        return PointsBalance;
    }

    public void setPointsBalance(String PointsBalance) {
        this.PointsBalance = PointsBalance;
    }

    public String getPrePaid() {
        return PrePaid;
    }

    public void setPrePaid(String PrePaid) {
        this.PrePaid = PrePaid;
    }

    public String getPreferentialRefund() {
        return PreferentialRefund;
    }

    public void setPreferentialRefund(String PreferentialRefund) {
        this.PreferentialRefund = PreferentialRefund;
    }

    public String getProvince() {
        return Province;
    }

    public void setProvince(String Province) {
        this.Province = Province;
    }

    public String getReserveFund() {
        return ReserveFund;
    }

    public void setReserveFund(String ReserveFund) {
        this.ReserveFund = ReserveFund;
    }

    public String getSettlementUnite() {
        return SettlementUnite;
    }

    public void setSettlementUnite(String SettlementUnite) {
        this.SettlementUnite = SettlementUnite;
    }

    public String getSettlementUniteName() {
        return SettlementUniteName;
    }

    public void setSettlementUniteName(String SettlementUniteName) {
        this.SettlementUniteName = SettlementUniteName;
    }

    public String getStationList() {
        return StationList;
    }

    public void setStationList(String StationList) {
        this.StationList = StationList;
    }

    public String getTelNo() {
        return TelNo;
    }

    public void setTelNo(String TelNo) {
        this.TelNo = TelNo;
    }


}
