package com.smallchill.modules.platform.model;


import com.alibaba.fastjson.annotation.JSONField;
import com.smallchill.core.base.model.BaseModel;
import com.smallchill.core.toolbox.kit.StrKit;
import org.beetl.sql.core.annotatoin.AssignID;
import org.beetl.sql.core.annotatoin.Table;

/**
 * Generated by Blade.
 * 2017-09-09 15:42:39
 */
@Table(name = "tb_station")
@SuppressWarnings("serial")
public class Station extends BaseModel {
    @AssignID
    private String id; //主键
    @JSONField(name = "StationNo")
    private String StationNo; //开户站点
    @JSONField(name = "StationAbbreviate")
    private String StationAbbreviate; //站点简称

    public String getId() {
        if (StrKit.isBlank(id))
            return StationNo;
        else
            return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public String getStationAbbreviate() {
        return StationAbbreviate;
    }

    public void setStationAbbreviate(String StationAbbreviate) {
        this.StationAbbreviate = StationAbbreviate;
    }

    public String getStationNo() {
        return StationNo;
    }

    public void setStationNo(String StationNo) {
        this.StationNo = StationNo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Station obj = (Station) o;
        if (!StationNo.equals(obj.StationNo)) return false;
        return StationAbbreviate.equals(obj.StationAbbreviate);
    }

    @Override
    public int hashCode() {
        int result = StationNo.hashCode();
        result = 31 * result + StationNo.hashCode();
        return result;
    }

}
