package com.smallchill.api.service;

import com.smallchill.api.model.Order;

/**
 * Generated by Blade.
 * 2017-10-18 16:49:02
 */
public interface ApiService  {

    /**
     * 创建订单
     * @param order
     * @return
     */
    boolean createOrder(Order order);

    /**
     * 圈存订单
     * @param id
     * @param charger
     * @return
     */
    boolean chargeOrder(Integer id, String charger);

    /**
     * 更改订单状态
     * @param orderId
     * @param status
     * @return
     */
    boolean changeStatus(Integer orderId, Integer status);

}
